import React from 'react';
import { motion } from 'framer-motion';
import Tippy from '@tippyjs/react'; // Tooltip library
import 'tippy.js/dist/tippy.css'; // Tooltip styles

const projects = [
  {
    name: 'DevDeck',
    description: 'Local-first macOS workspace for tracking repositories, branch review queues, pull requests, and development activity from one desktop interface.',
    github: 'https://github.com/ManuelCLopes/DevDeck',
    technologies: ['electron', 'react', 'typescript', 'vitejs', 'tailwindcss', 'nodejs'],
  },
  {
    name: 'francesinhas.top',
    description: 'A focused platform to evaluate francesinhas in Portugal with structured scoring, configurable weighted criteria, national rankings, restaurant insights, and community suggestions.',
    github: 'https://github.com/ManuelCLopes/francesinhas',
    demo: 'https://francesinhas.top',
    technologies: ['nextjs', 'typescript', 'tailwindcss', 'postgresql', 'prisma'],
  },
  {
    name: 'Competitor Watcher',
    description: 'AI-powered local competitor analysis platform. Competitor Watcher helps businesses understand their competitive landscape by analyzing nearby competitors using Google Places data and AI-driven insights. Register your business, generate comprehensive reports, and make data-driven decisions to stay ahead of the competition.',
    github: 'https://github.com/ManuelCLopes/radar',
    demo: 'https://competitorwatcher.pt',
    technologies: ['react', 'typescript', 'tailwindcss', 'nodejs', 'postgresql', 'googlecloud', 'chatgpt'],
  },
  {
    name: 'LeadOps.',
    description: 'A premium, high-conversion landing page for the "Lead Ops System" (Real Estate Lead Management). This static site allows agencies to capture leads and schedule demonstrations for a "Gmail-as-CRM" solution.',
    github: 'https://github.com/ManuelCLopes/real-estate-lead-ops',
    demo: 'https://tiny-snickerdoodle-eb2b4c.netlify.app',
    technologies: ['html', 'css'],
  },
  {
    name: 'GraphPathsCalculator',
    description: 'This C++ application was implemented in order to explore the capabilities of graphs.',
    github: 'https://github.com/ManuelCLopes/GraphPathsCalculator',
    technologies: ['cplusplus'],
  },
  {
    name: 'Restaurant Management Desktop App',
    description: 'This application was implemented in Python in order to helps the management of restaurants. I used Tkinter python module in front-end and PostgreSQL11 as database server.',
    github: 'https://github.com/ManuelCLopes/RestaurantManagement',
    technologies: ['python', 'postgresql'],
  },
  {
    name: 'EasyScan',
    description: 'Native OCR mobile application integrated with Firebase and Google Cloud Functions',
    github: 'https://github.com/ManuelCLopes/EasyScan',
    technologies: ['kotlin', 'googlecloud', 'firebase'],
  },
  {
    name: 'Real-time Monitoring Safety System',
    description: 'An Intelligent and Scalable IoT Monitoring Framework for Safety in Civil Construction workspaces and other sectors',
    github: 'https://link.springer.com/chapter/10.1007/978-3-031-14859-0_6',
    technologies: ['python', 'kafka', 'rabbitmq', 'activemq', 'docker'],
  },
  {
    name: 'Finance Tracker Mobile App',
    description: 'This is a Finance Tracker application built with Flutter, designed to help users manage their expenses, income, and investments efficiently. The app supports multiple languages and provides features such as adding transactions, calculating net worth, and viewing an overview of financial activities.',
    github: 'https://github.com/ManuelCLopes/finance_tracker',
    technologies: ['flutter', 'dart'],
  },
  {
    name: 'Finance Tracker Web App',
    description: 'A web-based application that allows users to visualize their financial data using various charts. Users can upload their financial data by scanning a QR code generated by the application and view the visualized data in real-time.',
    github: 'https://github.com/ManuelCLopes/finance_dashboard',
    technologies: ['python', 'django', 'javascript', 'heroku'],
  },
];

const techLogos = {
  html: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg', label: 'HTML' },
  css: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg', label: 'CSS' },
  python: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg', label: 'Python' },
  cplusplus: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg', label: 'C++' },
  postgresql: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg', label: 'PostgreSQL' },
  django: { url: 'https://www.svgrepo.com/show/353657/django-icon.svg', label: 'Django' },
  javascript: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg', label: 'Javascript' },
  react: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg', label: 'React' },
  docker: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg', label: 'Docker' },
  flutter: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg', label: 'Flutter' },
  dart: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dart/dart-original.svg', label: 'Dart' },
  firebase: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg', label: 'Firebase' },
  googlecloud: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg', label: 'GCP' },
  kotlin: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg', label: 'Kotlin' },
  rabbitmq: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rabbitmq/rabbitmq-original.svg', label: 'RabbitMQ' },
  activemq: { url: 'https://activemq.apache.org/assets/img/activemq_logo_icon.svg', label: 'ActiveMQ' },
  kafka: { url: 'https://openwhisk.apache.org/images/icons/icon-kafka-white-trans.png', label: 'Kafka' },
  heroku: { url: 'https://www.svgrepo.com/show/331424/heroku.svg', label: 'Heroku' },
  chatgpt: { url: 'https://img.icons8.com/androidL/512/FFFFFF/chatgpt.png', label: 'ChatGPT' },
  typescript: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg', label: 'TypeScript' },
  tailwindcss: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg', label: 'Tailwind CSS' },
  nodejs: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg', label: 'Node.js' },
  electron: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/electron/electron-original.svg', label: 'Electron' },
  vitejs: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vitejs/vitejs-original.svg', label: 'Vite' },
  nextjs: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg', label: 'Next.js', invert: true },
  prisma: { url: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/prisma/prisma-original.svg', label: 'Prisma', invert: true },
};

const Projects = () => {
  return (
    <div className="p-12 bg-gray-900 text-white">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {projects.map((project) => (

          <motion.div
            key={project.name}
            onClick={() => window.open(project.github, '_blank')}
            whileHover={{ scale: 1.05 }}
            className="relative p-6 bg-gray-800 rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300 border-2 border-transparent hover:border-blue-400 cursor-pointer group"
          >
            {project.demo && (
              <a
                href={project.demo}
                target="_blank"
                rel="noopener noreferrer"
                onClick={(e) => e.stopPropagation()}
                className="absolute top-4 right-4 text-gray-400 hover:text-blue-400 transition-colors duration-300 z-10"
                title="Live Demo"
              >
                <i className="fas fa-eye text-2xl"></i>
              </a>
            )}

            <h3 className="text-2xl font-bold mb-2 pr-8">{project.name}</h3>
            <p className="text-gray-400 mb-4">{project.description}</p>

            {project.features && (
              <ul className="list-disc list-inside text-gray-400 mb-4 text-sm">
                {project.features.map((feature, index) => (
                  <li key={index}>{feature}</li>
                ))}
              </ul>
            )}

            <div className="flex space-x-4 mb-4">
              {project.technologies.map((tech) => (
                <Tippy key={tech} content={techLogos[tech].label}>
                  <img
                    src={techLogos[tech].url}
                    alt={techLogos[tech].label}
                    className={`w-8 h-8 hover:scale-110 transition-transform ${techLogos[tech].invert ? 'invert' : ''}`}
                  />
                </Tippy>
              ))}
            </div>
          </motion.div>
        ))
        }
      </div>
    </div>
  );
};

export default Projects;
